const fs = require('fs');
const path = require('path');

function findHtmlFiles(dir, fileList = []) {
  const files = fs.readdirSync(dir);

  files.forEach(file => {
    const filePath = path.join(dir, file);
    if (fs.statSync(filePath).isDirectory()) {
      findHtmlFiles(filePath, fileList);
    } else if (path.extname(file) === '.html') {
      fileList.push(filePath);
    }
  });

  return fileList;
}

function prepareDeployment() {
  const htmlFiles = findHtmlFiles('.');
  const deployDir = './deploy';

  if (!fs.existsSync(deployDir)) {
    fs.mkdirSync(deployDir);
  }

  htmlFiles.forEach(file => {
    const relativePath = path.relative('.', file);
    const deployPath = path.join(deployDir, relativePath);
    const deployDir = path.dirname(deployPath);

    if (!fs.existsSync(deployDir)) {
      fs.mkdirSync(deployDir, { recursive: true });
    }

    fs.copyFileSync(file, deployPath);
    console.log(`Copied ${file} to ${deployPath}`);
  });

  console.log('Deployment preparation complete.');
}

prepareDeployment();
